version: "3"

services:
  jenkins:
    build:
      context: .
      dockerfile: dockerfile
    image: jenkins
    container_name: jenkins
    privileged: true
    hostname: jenkins
    user: root
    ports: 
      - "8080:8080"
      - "50000:50000"
    volumes: 
     - ./.backup:/var/jenkins_home
     - ../dev-portfolio:/home/dev-portfolio
     - /var/run/docker.sock:/var/run/docker.sock
    restart: always
